#!/usr/bin/env python3
"""Run the full Lineage Skill course pipeline.

Stages:
1. transcribe videos
2. analyze video frames and screenshots
3. distill course notes
4. package the result as a Codex skill
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def run(cmd: list[str], skip: bool) -> None:
    if skip:
        print(f"skip: {' '.join(cmd)}")
        return
    print(f"\n==> {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run transcription, visual analysis, distillation, and skill packaging.")
    parser.add_argument("--input-dir", required=True, help="Directory containing course .mp4 files.")
    parser.add_argument("--documents-input", action="append", help="Optional PDF file or directory for MinerU OCR. Repeatable.")
    parser.add_argument("--course-name", required=True, help="Course output directory name.")
    parser.add_argument("--skill-name", required=True, help="Generated skill name.")
    parser.add_argument("--mode", default="course-expert", help="Skill mode or comma-separated modes passed to build_course_skill.py.")
    parser.add_argument("--base-dir", default=str(ROOT), help="Course output root. Defaults to this repo.")
    parser.add_argument("--output-dir", default=str(ROOT / "dist"), help="Generated skill output directory.")
    parser.add_argument("--chunk-minutes", type=int, default=12, help="Video analysis chunk size.")
    parser.add_argument("--force", action="store_true", help="Re-run stages that support overwrite.")
    parser.add_argument("--skip-transcribe", action="store_true")
    parser.add_argument("--skip-analyze", action="store_true")
    parser.add_argument("--skip-documents", action="store_true")
    parser.add_argument("--skip-distill", action="store_true")
    parser.add_argument("--skip-package", action="store_true")
    parser.add_argument("--skip-build-skill", action="store_true")
    parser.add_argument("--limit", type=int, default=0, help="Limit video count for transcribe/analyze smoke runs.")
    args = parser.parse_args()

    py = sys.executable
    force = ["--force"] if args.force else []
    limit = ["--limit", str(args.limit)] if args.limit > 0 else []

    run(
        [
            py,
            str(ROOT / "scripts" / "transcribe_video.py"),
            "--input-dir",
            args.input_dir,
            "--course-name",
            args.course_name,
            "--base-dir",
            args.base_dir,
            *force,
            *limit,
        ],
        args.skip_transcribe,
    )
    run(
        [
            py,
            str(ROOT / "scripts" / "analyze_videos.py"),
            "--input-dir",
            args.input_dir,
            "--course-name",
            args.course_name,
            "--base-dir",
            args.base_dir,
            "--chunk-minutes",
            str(args.chunk_minutes),
            *force,
            *limit,
        ],
        args.skip_analyze,
    )
    if args.documents_input:
        doc_cmd = [
            py,
            str(ROOT / "scripts" / "parse_mineru_documents.py"),
            "--course-name",
            args.course_name,
            "--base-dir",
            args.base_dir,
        ]
        for item in args.documents_input:
            doc_cmd.extend(["--input", item])
        run(doc_cmd, args.skip_documents)
    run(
        [
            py,
            str(ROOT / "scripts" / "distill_course.py"),
            "--course-name",
            args.course_name,
            "--base-dir",
            args.base_dir,
        ],
        args.skip_distill,
    )
    run(
        [
            py,
            str(ROOT / "scripts" / "build_course_package.py"),
            "--course-name",
            args.course_name,
            "--source-dir",
            str(Path(args.base_dir) / args.course_name),
        ],
        args.skip_package,
    )
    run(
        [
            py,
            str(ROOT / "scripts" / "build_course_skill.py"),
            "--course-name",
            args.course_name,
            "--skill-name",
            args.skill_name,
            "--mode",
            args.mode,
            "--source-dir",
            str(Path(args.base_dir) / args.course_name),
            "--output-dir",
            args.output_dir,
            "--description",
            "Generated by the Lineage Skill full course pipeline.",
            *force,
        ],
        args.skip_build_skill,
    )


if __name__ == "__main__":
    main()
